# **Assignment: Python Lists Practice**

##**Easy Questions:**

In [4]:
def filter_even_numbers(num):
  return [x for x in num if x % 2 == 0]
print(filter_even_numbers([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
print(filter_even_numbers([834,58673,702,270]))
print(filter_even_numbers([1, 3, 5, 7, 9,89,76,45,34,9086,6645]))

[2, 4, 6, 8, 10]
[834, 702, 270]
[76, 34, 9086]


In [3]:
def merge_sorted_lists(list1,list2):
  return sorted(list1 + list2)
print(merge_sorted_lists([76,90,54,36,987,789,654], [44,90,87,65,12,890,789,564]))

[12, 36, 44, 54, 65, 76, 87, 90, 90, 564, 654, 789, 789, 890, 987]


##**Medium Questions:**

In [7]:
import numpy as np
def generate_matrix(r,c):
  matrix = np.zeros((r,c), dtype=int)
  for i in range(r):
    for j in range(c):
      matrix[i,j]=i*j
  return matrix
print(generate_matrix(4,5))
print(generate_matrix(2,3))
print(generate_matrix(3,3))
print(generate_matrix(3,4))


[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]]
[[0 0 0]
 [0 1 2]]
[[0 0 0]
 [0 1 2]
 [0 2 4]]
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]


In [14]:
def transpose_matrix(matrix):
    r = len(matrix)
    c = len(matrix[0])
    transpose = [[0 for _ in range(r)] for _ in range(c)]
    for i in range(r):
        for j in range(c):
            transpose[j][i] = matrix[i][j]
    return transpose
# Print function to format output as matrix
def print_matrix(matrix):
    for row in matrix:
        print(row)
    print("\n")
matrix1 = [[1, 5, 7],
           [3, 0, 9],
           [2, 1, 6]]
matrix2 = [[1, 2, 3],
           [7, 8, 9]]
matrix3 = [[1, 9],
           [2, 8],
           [3, 7]]
print_matrix(transpose_matrix(matrix1))
print_matrix(transpose_matrix(matrix2))
print_matrix(transpose_matrix(matrix3))


[1, 3, 2]
[5, 0, 1]
[7, 9, 6]


[1, 7]
[2, 8]
[3, 9]


[1, 2, 3]
[9, 8, 7]




##**Hard Questions:**


In [2]:
def find_peaks(nums):
    peaks = []
    for i in range(1, len(nums) - 1):
        if nums[i] > nums[i - 1] and nums[i] > nums[i + 1]:
            peaks.append(i)
    return peaks
print(find_peaks([1, 3, 2, 3, 5, 4, 3, 2, 3, 1]))
print(find_peaks([2,7,9,3,6,54,90,81]))


[1, 4, 8]
[2, 6]


In [3]:
def rotate_List(list,k):
  k=k%len(list)
  for _ in range(k):
    last=list.pop()
    list.insert(0,last)
    return list
print(rotate_List([1, 2, 3, 4, 5], 2))
print(rotate_List([1, 2, 3], 4))
print(rotate_List([3,2,0,8,54,78,12],5))

[5, 1, 2, 3, 4]
[3, 1, 2]
[12, 3, 2, 0, 8, 54, 78]
